### ISSUE TITLE
Inconsistent Hanging When Creating Client

### ISSUE THREAD

**Issue by negodfre** [t-wolfeadam/Alpyne#11]
Hello,
I am having inconsistencies with the simulation not starting when creating the AlpyneClient().
While I was able to reproduce issues when the database checkbox was or wasn't checked, I have not been able to determine why other times the creation of the client hangs.

**Code:**
`client = AlpyneClient(r"Exported1\model.jar", blocking=True, verbose=True)`

**Example:**
This morning I have been having issues where  the program will hang.
At first, no matter what I did the simulation would hang.

The log would show:
`[2021-11-22 11:56:22] INFO    @ com.anylogic.alpyne.AlpyneServer main 
                              | [PID=24648] Initializing @ 'C:\Users\test_user\Models\test_example\Exported1' with arguments: {path=., port=51150, dev_mode=false}
[2021-11-22 11:56:22] FINER   @ ModelManager.<init>
                              | ENTRY {0}	.
[2021-11-22 11:56:22] FINER   @ BonsaiBrainLearningPlatform.<init>
                              | ENTRY {0}	{}
[2021-11-22 11:56:22] INFO    @ Version.load
                              | Loading from experiment
[2021-11-22 11:56:30] INFO    @ Version.load
                              | Inputs      = [(BOOLEAN)x_one=null, (BOOLEAN)x_two=null, (BOOLEAN)x_three=null, (BOOLEAN)x_four=null, (BOOLEAN)x_five=null, (BOOLEAN)x_six=null, (BOOLEAN)x_seven=null, (BOOLEAN)x_eight=null, (BOOLEAN)inRLMode=null, (DOUBLE){START_TIME}=0.0, (DATE_TIME){START_DATE}=Tue Dec 31 22:00:00 EST 2019, (DOUBLE){STOP_TIME}=336.0833333333333, (DATE_TIME){STOP_DATE}=Wed Dec 02 00:00:00 EST 2020, (LONG){RANDOM_SEED}=null]
                                Outputs     = [(DOUBLE)rewardOut=null]
                                Config      = [(INTEGER)cfg_var_one=null, (INTEGER)cfg_var_two=null, (INTEGER)cfg_var_three=null, (INTEGER)cfg_var_four=null, (INTEGER)cfg_var_five=null, (INTEGER)cfg_var_six=null, (INTEGER)cfg_var_seven=null, (INTEGER)cfg_var_eight=null, (DOUBLE){START_TIME}=0.0, (DATE_TIME){START_DATE}=Tue Dec 31 22:00:00 EST 2019, (DOUBLE){STOP_TIME}=336.0833333333333, (DATE_TIME){STOP_DATE}=Wed Dec 02 00:00:00 EST 2020, (LONG){RANDOM_SEED}=null]
                                Observation = [(DOUBLE_ARRAY)varOne=null, (DOUBLE_ARRAY)varTwo=null, (DOUBLE)varThree=null]
                                Action      = [(INTEGER)next_var=null]
[2021-11-22 11:56:30] WARNING @ org.glassfish.jersey.server.wadl.WadlFeature configure 
                              | JAX-B API not found . WADL feature is disabled.
[2021-11-22 11:56:31] INFO    @ org.glassfish.grizzly.http.server.NetworkListener start 
                              | Started listener bound to [localhost:51150]
[2021-11-22 11:56:31] INFO    @ org.glassfish.grizzly.http.server.HttpServer start 
                              | [HttpServer] Started.`

I restarted my computer. 
Then, I re-exported the AnyLogic model & unzipped the model.
I was then able to run the simulation no problem. 

However, when I kill the terminal in VSCode & tried again, it hangs (no changes to model.jar or python script).
I kill the terminal again & try again & the program runs fine.

Based on the log it seemed the address was still in use even though the program was killed:
`[2021-12-02 05:47:06] SEVERE  @ com.anylogic.alpyne.AlpyneServer main 
                              | Issue while attempting to run server: Failed to start Grizzly HTTP server: Address already in use: bind
jakarta.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Address already in use: bind
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:270)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:93)
	at com.anylogic.alpyne.AlpyneServer.startServer(AlpyneServer.java:52)
	at com.anylogic.alpyne.AlpyneServer.main(AlpyneServer.java:94)
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bindToChannelAndAddress(TCPNIOBindingHandler.java:95)
	at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind(TCPNIOBindingHandler.java:63)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:224)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:207)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:199)
	at org.glassfish.grizzly.http.server.NetworkListener.start(NetworkListener.java:740)
	at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:234)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:267)
	... 3 more`

Would there be any tips to reduce issues with the program hanging during the client creation?

**Comment by negodfre** [comment]
rokitamer's solution fixed this for me:
Update: In order for the AlpyneClient to work, I had to add a waiting time in it's initialization (time.sleep(5) on line 46 @alpine_client.py).
