### ISSUE TITLE
fail to connect with client

### ISSUE THREAD

**Issue by cory1219** [t-wolfeadam/Alpyne#22]
Hello,

I am using windows and both my java and javac version are 18.0.2.1 and anylogic 8.8.0 professional. My log and error meesage is as follows. Can someone help me with it? thanks! :

2022-09-06 11:08:25,750 [alpyne.client.alpyne_client @ 72][    INFO] Starting model in C:\Users\TuM\Desktop\Alpyne-main\Alpyne-main\examples\Stock Management Game\Exported\StockManagementGame
2022-09-06 11:08:25,751 [alpyne.client.alpyne_client @ 92][   DEBUG] Executing:
java -cp C:\Users\TuM\Anaconda3\lib\site-packages\alpyne\resources\*;C:\Users\TuM\Anaconda3\lib\site-packages\alpyne\resources\alpyne_lib\*;* com.anylogic.alpyne.AlpyneServer -p 51150 -o C:\Users\TuM\Desktop\Alpyne-main\Alpyne-main\examples\Stock Management Game -l ALL .

2022-09-06 11:08:25,761 [alpyne.client.alpyne_client @ 110][    INFO] Started app | PID = 14884
2022-09-06 11:08:25,761 [alpyne.client.http_client @ 30][   DEBUG] GET /versions/number/0: None
Traceback (most recent call last):
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 946, in connect
    self.sock = self._create_connection(
  File "C:\Users\TuM\Anaconda3\lib\socket.py", line 844, in create_connection
    raise err
  File "C:\Users\TuM\Anaconda3\lib\socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TuM\Anaconda3\lib\site-packages\alpyne\client\alpyne_client.py", line 49, in __init__
    _, _, output = self._http_client.get("/versions/number/0")
  File "C:\Users\TuM\Anaconda3\lib\site-packages\alpyne\client\http_client.py", line 57, in get
    return self.api_request(url, method="GET")
  File "C:\Users\TuM\Anaconda3\lib\site-packages\alpyne\client\http_client.py", line 38, in api_request
    response = urllib.request.urlopen(request, timeout=3)
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TuM\Desktop\Alpyne-main\Alpyne-main\examples\Stock Management Game\rlpolicy_train.py", line 79, in <module>
    client = AlpyneClient(r"Exported\StockManagementGame\model.jar", verbose=True)
  File "C:\Users\TuM\Anaconda3\lib\site-packages\alpyne\client\alpyne_client.py", line 52, in __init__
    raise ModelError(f"Failed to properly start the app. Error from process: {self._proc.stderr.readline().decode()}")
alpyne.data.model_error.ModelError: ModelError[path=, status=Failed to properly start the app. Error from process: , error=None, msg='']
2022-09-06 11:08:27,809 [alpyne.client.http_client @ 30][   DEBUG] DELETE /: None
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\TuM\Anaconda3\lib\http\client.py", line 946, in connect
    self.sock = self._create_connection(
  File "C:\Users\TuM\Anaconda3\lib\socket.py", line 844, in create_connection
    raise err
  File "C:\Users\TuM\Anaconda3\lib\socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TuM\Anaconda3\lib\site-packages\alpyne\client\http_client.py", line 38, in api_request
    response = urllib.request.urlopen(request, timeout=3)
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\TuM\Anaconda3\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte>

**Comment by t-wolfeadam** [comment]
Hi, it may be a problem with the startup of the connector. There was a fix that I haven't pushed to pypi yet, so you can either download the repo and install from there. Alternatively, you can manually apply the change by updating the `http_client.py` file with the one in this repo ([here](https://github.com/t-wolfeadam/Alpyne/blob/main/alpyne/client/http_client.py)).

**Comment by gjones1911** [comment]
I am running into the same issue. The problem does seem to be coming from the http_client.py file, but I also have the updated version. Any Ideas?

**Comment by t-wolfeadam** [comment]
Closing as this is likely resolved in v1.0.0. Feel free to create a new issue if it remains.
