### ISSUE TITLE
Connection Refused Error with alpyne.log throwing multiple errors

### ISSUE THREAD

**Issue by tommycq** [t-wolfeadam/Alpyne#26]
Hello all,

I am trying to run the stock management game sample model, with the updated `http_client.py` and java/javac version 19.0.1.

However I am still having the error with the startup of the connector ("WinError 10061: ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it")

I have checked the alpyne.log and I have realised that there are multiple errors raised. May I know how the problem can be solved here, or what has probably gone wrong? Thanks.

```
[2022-10-23` 22:13:47] INFO    @ com.anylogic.alpyne.AlpyneServer main 
                              | [PID=84648] Initializing @ 'path/Stock Management Game/Exported/StockManagementGame' with arguments: {path=., port=51150, dev_mode=false}
[2022-10-23 22:13:47] INFO    @ AlpyneServer.main
                              | [PID=84648] Initializing @ 'path/Stock Management Game/Exported/StockManagementGame' with arguments: {path=., port=51150, dev_mode=false}

[2022-10-23 22:13:47] SEVERE  @ com.anylogic.alpyne.AlpyneServer main 
                              | Issue while attempting to run server: null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at com.anylogic.alpyne.sim.api.JarReader.getRLExperiment(JarReader.java:40)
	at com.anylogic.alpyne.sim.ModelManager.<init>(ModelManager.java:42)
	at com.anylogic.alpyne.AlpyneServer.main(AlpyneServer.java:93)
Caused by: java.lang.NoClassDefFoundError: com/querydsl/sql/RelationalPath
	at com.anylogic.engine.ExperimentCustom.<init>(Unknown Source)
	at com.anylogic.engine.ExperimentReinforcementLearning.<init>(Unknown Source)
	at com.anylogic.engine.ExperimentReinforcementLearning.<init>(Unknown Source)
	at stock_management_game1.RLExperiment.<init>(RLExperiment.java:90)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.querydsl.sql.RelationalPath
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more

[2022-10-23 22:13:47] WARNING @ com.anylogic.alpyne.AlpyneServer main 
                              | Alpyne terminated.
[2022-10-23 22:13:47] SEVERE  @ AlpyneServer.main
                              | Issue while attempting to run server: null
                                java.lang.reflect.InvocationTargetException
                                	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79)
                                	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
                                	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
                                	at com.anylogic.alpyne.sim.api.JarReader.getRLExperiment(JarReader.java:40)
                                	at com.anylogic.alpyne.sim.ModelManager.<init>(ModelManager.java:42)
                                	at com.anylogic.alpyne.AlpyneServer.main(AlpyneServer.java:93)
                                Caused by: java.lang.NoClassDefFoundError: com/querydsl/sql/RelationalPath
                                	at com.anylogic.engine.ExperimentCustom.<init>(Unknown Source)
                                	at com.anylogic.engine.ExperimentReinforcementLearning.<init>(Unknown Source)
                                	at com.anylogic.engine.ExperimentReinforcementLearning.<init>(Unknown Source)
                                	at stock_management_game1.RLExperiment.<init>(RLExperiment.java:90)
                                	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
                                	... 5 more
                                Caused by: java.lang.ClassNotFoundException: com.querydsl.sql.RelationalPath
                                	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
                                	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
                                	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
                                	... 10 more
                                
[2022-10-23 22:13:47] WARNING @ AlpyneServer.main
                              | Alpyne terminated.
```

**Comment by ggkaggk** [comment]
Recently, I have had a similar problem, may I ask if your situation is solved?

**Comment by t-wolfeadam** [comment]
The error `Caused by: java.lang.ClassNotFoundException: com.querydsl.sql.RelationalPath` means that there are missing libraries. Please try re-exporting the model and trying again.
