### ISSUE TITLE
Error During Testing My Own RL Experiment with Code from Simple Run

### ISSUE THREAD

**Issue by m1ng2e** [t-wolfeadam/Alpyne#35]
Hi, 
I used the code in _simple run - single.py_ for the stock management game example to test it on my own RL experiment. But the following bug popped up. 
_AnyLogic Version: University 8.8.1
Alpyne Version: 0.2.0
Java Version: 19.0.1
Python Version: 3.8.8_
I have attached my full log here.
Could anyone help me on this? Thank you.

```
Exception during discrete event execution:
Cannot invoke "com.anylogic.engine.EventOriginator.execute()" because "this.dg" is null
java.lang.NullPointerException: Cannot invoke "com.anylogic.engine.EventOriginator.execute()" because "this.dg" is null
	at com.anylogic.engine.Engine.f(Unknown Source)
	at com.anylogic.engine.Engine.runFast(Unknown Source)
	at com.anylogic.engine.Engine.runFast(Unknown Source)
	at com.anylogic.rl.connector.bonsai.BonsaiBrainLearningPlatform.run(BonsaiBrainLearningPlatform.java:271)
	at com.anylogic.alpyne.sim.api.ModelRunPlatform.run(ModelRunPlatform.java:224)
```
[alpyne.log](https://github.com/t-wolfeadam/Alpyne/files/10323497/alpyne.log)

**Comment by t-wolfeadam** [comment]
Closing as this is likely resolved in v1.0.0. Feel free to create a new issue if it remains.
