### ISSUE TITLE
Problems with the updated version of Anylogic 8.8.2 and Material Handling Library

### ISSUE THREAD

**Issue by marigmarch** [t-wolfeadam/Alpyne#38]
I am encountering an issue with Anylogic 8.8.2 and the Alpyne library. This is the error in the log file:

[2023-03-30 12:53:29] INFO    @ com.anylogic.alpyne.AlpyneServer main 
                              | [PID=10508] Initializing @ 'C:\Users\MG Marchesano\Models\AI_FlowShop_modificatoSPT\Mod9' with arguments: {path=., port=51150, dev_mode=false}
[2023-03-30 12:53:31] WARNING @ org.glassfish.jersey.server.wadl.WadlFeature configure 
                              | JAX-B API not found . WADL feature is disabled.
[2023-03-30 12:53:31] INFO    @ org.glassfish.grizzly.http.server.NetworkListener start 
                              | Started listener bound to [localhost:51150]
[2023-03-30 12:53:31] INFO    @ org.glassfish.grizzly.http.server.HttpServer start 
                              | [HttpServer] Started.
[2023-03-30 12:53:32] SEVERE  @ BonsaiBrainLearningPlatform.processExperimentError
                              | executing model
                                java.lang.ClassCastException: class [Lcom.anylogic.engine.presentation.ModelElementDescriptor; cannot be cast to class [Lcom.anylogic.engine.presentation.ModelElementDescriptorUtils; ([Lcom.anylogic.engine.presentation.ModelElementDescriptor; and [Lcom.anylogic.engine.presentation.ModelElementDescriptorUtils; are in unnamed module of loader 'app')
                                	at modello1.Main.doCreate(Main.java:2948)
                                	at com.anylogic.engine.Agent.createAsEmbedded(Unknown Source)
                                	at com.anylogic.engine.Agent.create(Unknown Source)
                                	at com.anylogic.engine.Engine.start(Unknown Source)
                                	at com.anylogic.rl.connector.bonsai.BonsaiBrainLearningPlatform.run(BonsaiBrainLearningPlatform.java:239)
                                	at com.anylogic.alpyne.sim.api.ModelRunPlatform.run(ModelRunPlatform.java:224)
                                
Exception in thread "Thread-0" java.lang.RuntimeException: root:
Error - executing model
	at com.anylogic.engine.Engine.error(Unknown Source)
	at com.anylogic.engine.Agent.error(Unknown Source)
	at com.anylogic.engine.Utilities.error(Unknown Source)
	at com.anylogic.rl.connector.bonsai.BonsaiBrainLearningPlatform.processExperimentError(BonsaiBrainLearningPlatform.java:710)
	at com.anylogic.rl.connector.bonsai.BonsaiBrainLearningPlatform.run(BonsaiBrainLearningPlatform.java:304)
	at com.anylogic.alpyne.sim.api.ModelRunPlatform.run(ModelRunPlatform.java:224)
Caused by: java.lang.ClassCastException: class [Lcom.anylogic.engine.presentation.ModelElementDescriptor; cannot be cast to class [Lcom.anylogic.engine.presentation.ModelElementDescriptorUtils; ([Lcom.anylogic.engine.presentation.ModelElementDescriptor; and [Lcom.anylogic.engine.presentation.ModelElementDescriptorUtils; are in unnamed module of loader 'app')
	at modello1.Main.doCreate(Main.java:2948)
	at com.anylogic.engine.Agent.createAsEmbedded(Unknown Source)
	at com.anylogic.engine.Agent.create(Unknown Source)
	at com.anylogic.engine.Engine.start(Unknown Source)
	at com.anylogic.rl.connector.bonsai.BonsaiBrainLearningPlatform.run(BonsaiBrainLearningPlatform.java:239)
	... 1 more
[2023-03-30 12:53:33] INFO    @ com.anylogic.alpyne.AlpyneServer main 
                              | Terminating app...
[2023-03-30 12:53:33] INFO    @ org.glassfish.grizzly.http.server.NetworkListener shutdownNow 
                              | Stopped listener bound to [localhost:51150]
[2023-03-30 12:53:33] WARNING @ com.anylogic.alpyne.AlpyneServer main 
                              | Alpyne terminated.
[2023-03-30 12:53:29] INFO    @ AlpyneServer.main
                              | [PID=10508] Initializing @ 'C:\Users\MG Marchesano\Models\AI_FlowShop_modificatoSPT\Mod9' with arguments: {path=., port=51150, dev_mode=false}
[2023-03-30 12:53:33] INFO    @ AlpyneServer.main
                              | Terminating app...
[2023-03-30 12:53:33] WARNING @ AlpyneServer.main
                              | Alpyne terminated.

When I run the same code with an exported model made with Anylogic 8.8.1 it's all fine.

Regarding the second issue, there are some problems when using Material Handling Library in models that will be used in Alpyne. I managed to solve the problem not using the library but I think it is something you should know.

**Comment by rokitatomer** [comment]
Hello - I am having the same problem with 8.8.2 (and I am not using the Material Handling Library).

**Comment by mjhoover1** [comment]
I am having the same issue too and not using the Material Handling Library.

**Comment by marigmarch** [comment]
@mjhoover1 @rokitatomer I avoided the issue by using version 8.8.1, but I have contacted Anylogic Support to obtain further information.

**Comment by rokitatomer** [comment]
Thank you  for your reply. How can I get previous versions of Anylogic, such as 8.8.1? Their website offers only the latest version, and I didn't keep a copy of the previous version.

**Comment by marigmarch** [comment]
[anylogic-university-8.8.1.x86_64.zip](https://github.com/t-wolfeadam/Alpyne/files/11223397/anylogic-university-8.8.1.x86_64.zip)
try this @rokitatomer

**Comment by rokitatomer** [comment]
Thanks - but the link doesn't work, it has a file with a size of 0 KB.

**Comment by mjhoover1** [comment]
Does this work? https://drive.google.com/file/d/1QqxSZLNbYsNaryetKAyg0KR5ZPNYH4Iy/view?usp=sharing

**Comment by rokitatomer** [comment]
Thank you - but I am using Windows...

**Comment by marigmarch** [comment]
Sorry @rokitatomer wrong file https://we.tl/t-I6B14u7Byq try this

**Comment by t-wolfeadam** [comment]
Closing as this is likely resolved in v1.0.0. Feel free to create a new issue if it remains.
