### ISSUE TITLE
MODEL_ERROR thrown from wait_for_completion() 

### ISSUE THREAD

**Issue by mjhoover1** [t-wolfeadam/Alpyne#39]
I have been getting an error during the training process and it's hard to determine what the issue is. I know the issue occurs when the wait_for_completion() function is called from Anylogic after the takeAction() and getObservation() functions are called. However, I have tried using verbose = True and the alpyne log doesn't give any useful information. The issue is also difficult to debug since it happens randomly during training and occurs when the model is querying Anylogic. This is the resulting stack trace:

```
Traceback (most recent call last):
  File "/home/ubuntuAdmin/RL-supplyChain/examples/ProductDelivery/load_model.py", line 81, in <module>
    model.learn(TIME_STEPS, reset_num_timesteps=False, tb_log_name="PPO")
  File "/home/ubuntuAdmin/.local/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py", line 307, in learn
    return super().learn(
  File "/home/ubuntuAdmin/.local/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 248, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/home/ubuntuAdmin/.local/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 175, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
  File "/home/ubuntuAdmin/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 163, in step
    return self.step_wait()
  File "/home/ubuntuAdmin/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 54, in step_wait
    obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
  File "/home/ubuntuAdmin/.local/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 94, in step
    observation, reward, done, info = self.env.step(action)
  File "/usr/local/lib/python3.8/dist-packages/anylogic_alpyne-0.2.0-py3.8.egg/alpyne/client/abstract.py", line 240, in step
    self.sim.wait_for_completion()
  File "/usr/local/lib/python3.8/dist-packages/anylogic_alpyne-0.2.0-py3.8.egg/alpyne/client/model_run.py", line 118, in wait_for_completion
    raise ModelError(info)
alpyne.data.model_error.ModelError: ModelError[path=, status={'reason': 'MODEL_ERROR', 'next_event_time': 2282.6373817024883, 'episode_count': 19, 'step_count': 97, 'model_time': 2282.6373817024883}, error=None, msg='']
```

Has anyone else had this issue and determined how to resolve it? Thanks.

**Comment by mjhoover1** [comment]
I believe I figured it out, there was a race condition in the model.
