### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] when running the example

### ISSUE THREAD

**Issue by zhixin-zhao** [t-wolfeadam/Alpyne#41]
I installed Alpyne in python3.9 conda env and download the project and then run the example in `Traffic Light` fold: 
```bash
& C:/Users/zzxin/anaconda3/envs/alpyne/python.exe "c:/Users/zzxin/Desktop/Alpyne-main/examples/Traffic Light/script.py"
``` 
Here is the error: 
```
2023-05-05 22:39:57,317 [alpyne.client.alpyne_client @ 72][    INFO] Starting model in C:\Users\zzxin\Desktop\Alpyne-main\examples\Traffic Light\Exported\Traffic Light RL
2023-05-05 22:39:57,319 [alpyne.client.alpyne_client @ 92][   DEBUG] Executing:
java -cp C:\Users\zzxin\anaconda3\envs\alpyne\lib\site-packages\alpyne\resources\*;C:\Users\zzxin\anaconda3\envs\alpyne\lib\site-packages\alpyne\resources\alpyne_lib\*;*;3d\*;database\* com.anylogic.alpyne.AlpyneServer -p 51150 -o C:\Users\zzxin\Desktop\Alpyne-main\examples\Traffic Light -l ALL .

2023-05-05 22:39:57,326 [alpyne.client.alpyne_client @ 110][    INFO] Started app | PID = 2676
2023-05-05 22:39:57,326 [alpyne.client.http_client @ 30][   DEBUG] GET /versions/number/0: None
Traceback (most recent call last):
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 946, in connect
    self.sock = self._create_connection(
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\socket.py", line 844, in create_connection
    raise err
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it.>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\site-packages\alpyne\client\alpyne_client.py", line 49, in __init__    
    _, _, output = self._http_client.get("/versions/number/0")
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\site-packages\alpyne\client\http_client.py", line 57, in get
    return self.api_request(url, method="GET")
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\site-packages\alpyne\client\http_client.py", line 38, in api_request   
    response = urllib.request.urlopen(request, timeout=3)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it.>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\zzxin\Desktop\Alpyne-main\examples\Traffic Light\script.py", line 9, in <module>
    client = AlpyneClient(r"Exported\Traffic Light RL\model.jar", blocking=True, port = 51150,  verbose=True)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\site-packages\alpyne\client\alpyne_client.py", line 52, in __init__    
    raise ModelError(f"Failed to properly start the app. Error from process: {self._proc.stderr.readline().decode()}")  
alpyne.data.model_error.ModelError: ModelError[path=, status=Failed to properly start the app. Error from process: , error=None, msg='']
2023-05-05 22:39:59,394 [alpyne.client.http_client @ 30][   DEBUG] DELETE /: None
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\http\client.py", line 946, in connect
    self.sock = self._create_connection(
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\socket.py", line 844, in create_connection
    raise err
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\site-packages\alpyne\client\http_client.py", line 38, in api_request   
    response = urllib.request.urlopen(request, timeout=3)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\zzxin\anaconda3\envs\alpyne\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it.>
```

**Comment by zhixin-zhao** [comment]
By the way, [specifying full path name for the file passed to the AlpyneClient](https://github.com/t-wolfeadam/Alpyne/issues/27#issuecomment-1318994466) dosen't work

**Comment by t-wolfeadam** [comment]
Closing as this is likely resolved in v1.0.0. Feel free to create a new issue if it remains.
