### ISSUE TITLE
rlpolicy_train.py Stock Management Game Example

### ISSUE THREAD

**Issue by negodfre** [t-wolfeadam/Alpyne#5]
Hello,

I was trying out the rlpolicy_train.py file for the Stock Management Game, but I was unable to get it to run.

The error I get is "Expected data element 'order_rate' to be declared as (or less than) type 'DOUBLE'; received type 'OBJECT'".

**Current Code**
` def _convert_to_action(self, action: float) -> Action:
        return Action(order_rate=action)`

**Versions:**
AnyLogic Software  8.7.7
anylogic-alpyne      0.2.0
stable_baselines3   1.3.0
gym                         0.19.0

**Error Log:**
[2021-11-17 10:12:23] INFO    @ com.anylogic.alpyne.AlpyneServer main 
                              | [PID=12248] Initializing @ 'C:\Users\naog\Models\Alpyne\examples\StockManagementGame\Exported\StockManagementGame' with arguments: {path=., port=51150, dev_mode=false}
[2021-11-17 10:12:24] WARNING @ org.glassfish.jersey.server.wadl.WadlFeature configure 
                              | JAX-B API not found . WADL feature is disabled.
[2021-11-17 10:12:25] INFO    @ org.glassfish.grizzly.http.server.NetworkListener start 
                              | Started listener bound to [localhost:51150]
[2021-11-17 10:12:25] INFO    @ org.glassfish.grizzly.http.server.HttpServer start 
                              | [HttpServer] Started.
[2021-11-17 10:12:26] SEVERE  @ ModelManager.executeRequest
                              | Problem executing request
                                java.util.InputMismatchException: Expected data element 'order_rate' to be declared as (or less than) type 'DOUBLE'; received type 'OBJECT'
                                	at com.anylogic.alpyne.server.data.Version.validate(Version.java:235)
                                	at com.anylogic.alpyne.server.data.Version.validate(Version.java:200)
                                	at com.anylogic.alpyne.sim.ModelManager.executeRequest(ModelManager.java:99)
                                	at com.anylogic.alpyne.server.api.RunsResource.executeRLCommand(RunsResource.java:240)
                                	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                                	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                                	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
                                	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
                                	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
                                	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
                                	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
                                	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
                                	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
                                	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
                                	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
                                	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
                                	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
                                	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
                                	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
                                	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
                                	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
                                	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
                                	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
                                	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356)
                                	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190)
                                	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
                                	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
                                	at java.base/java.lang.Thread.run(Thread.java:833)
                                
[2021-11-17 10:12:26] INFO    @ com.anylogic.alpyne.AlpyneServer main 
                              | Terminating app...
[2021-11-17 10:12:26] INFO    @ org.glassfish.grizzly.http.server.NetworkListener shutdownNow 
                              | Stopped listener bound to [localhost:51150]
[2021-11-17 10:12:26] WARNING @ com.anylogic.alpyne.AlpyneServer main 
                              | Alpyne terminated.
[2021-11-17 10:12:23] INFO    @ AlpyneServer.main
                              | [PID=12248] Initializing @ 'C:\Users\naog\Models\Alpyne\examples\StockManagementGame\Exported\StockManagementGame' with arguments: {path=., port=51150, dev_mode=false}
[2021-11-17 10:12:26] INFO    @ AlpyneServer.main
                              | Terminating app...
[2021-11-17 10:12:26] WARNING @ AlpyneServer.main
                              | Alpyne terminated.

**Comment by t-wolfeadam** [comment]
Thanks for reporting this and for providing all the relevant information!

I got a chance to look into it today and, for the `_convert_to_action` method, I incorrectly assumed the `action` argument is a float; in reality, it's a 1-length numpy array. The "OBJECT" type is just a fallback for non-handled types (e.g., numpy arrays). The fix - which will be pushed shortly and part of the next release - is to simply extract the value from the array (and fix the annotation), as follows:

```python
def _convert_to_action(self, action: np.ndarray) -> Action:
        return Action(order_rate=float(action[0]))
```
