### ISSUE TITLE
"500 Server Error" when configuration and/or observation space is empty

### ISSUE THREAD

**Issue by t-wolfeadam** [t-wolfeadam/Alpyne#52]
When trying to reset a sim with no fields in the configuration or the observation, an exception is thrown on resetting. Example script/output:

```python
>>> sim = AnyLogicSim("Model353.zip")                                         
>>> print(sim.schema)
SimSchema
=========
input = {

}
outputs = {

}
configuration = {

}
engine_settings = {
    'seed': FieldData(name='seed', type='long', value=None, units=None),
    'start_date': FieldData(name='start_date', type='Date', value='2024-03-18T05:00:00.000+00:00', units=None),
    'start_time': FieldData(name='start_time', type='Double', value=0.0, units=None),
    'stop_date': FieldData(name='stop_date', type='Date', value='2024-03-18T05:01:40.000+00:00', units=None),
    'stop_time': FieldData(name='stop_time', type='Double', value=100.0, units=None),
    'units': FieldData(name='units', type='TimeUnits', value='SECOND', units=None)
}
observation = {

}
action = {

}

>>> sim.reset()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\twolf\Documents\PythonWorkspace\Alpyne\alpyne\sim.py", line 354, in reset
    _ = self._request("PUT", "rl", data=dict(configuration=_config, engine_settings=self.engine_settings))
  File "C:\Users\twolf\Documents\PythonWorkspace\Alpyne\alpyne\sim.py", line 327, in _request
    raise HTTPError(error_msg)
requests.exceptions.HTTPError: 500 Server Error: UNHANDLED EXCEPTION; SEE LOGS. for url http://127.0.0.1:50471/rl -- check alpyne.log for more info
```

And relevant snippet of alpyne.log:

```
[2024-03-18 15:48:07.622] SEVERE  @ RLResource.rlResetRun
                              | UNHANDLED EXCEPTION (class java.lang.IllegalArgumentException)
                                java.lang.IllegalArgumentException: No serializer found for class model353.RLExperiment$Configuration and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.anylogic.alpyne.sim.data.ModelRequestReset["configuration"])
```

If the configuration space has at least one field but the observation space does not, a similar error will occur. This is because both assume you have at least one field in each. The action space does not have this issue (i.e., it can be empty).

So the workaround for now is to put some dummy field in the configuration/observation if you do not have any (it doesn't have to be assigned or used).

**Comment by t-wolfeadam** [comment]
Fixed in #58
