### ISSUE TITLE
App fails to start; model.log reports "UnsupportedClassVersionError"

### ISSUE THREAD

**Issue by t-wolfeadam** [t-wolfeadam/Alpyne#56]
Python logs report "ModelError[path=, status=The underlying application failed to start. Check the logs., error=None, msg='']".

Full stack trace in model.log:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/anylogic/engine/ReinforcementLearningModel has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.anylogic.alpyne.AlpyneServer.main(AlpyneServer.java:131)
```

**Comment by t-wolfeadam** [comment]
Fixed in #58
